# Generated by Django 5.2.14 on 2026-10-02 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_ui', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Author',
            new_name='author',
        ),
    ]
